config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :reviews, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: RATING }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_id, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(create_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update

  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_id
    @restaurant = Restaurant.find(params[:id])
  end

  def create_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

  def update_params
    params.require(:restaurant).permit(:address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(restaurant_id: params[:restaurant_id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(check_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def check_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="m-4 pr-4 pl-4">
  <%= simple_form_for @restaurant do |f| %>

    <%= f.input :name %>
    <%= f.input :address %>

    <%= f.input :category, collection: Restaurant::CATEGORIES  %>
    <%= f.input :phone_number %>
    <%= f.button :submit, class: "btn btn-primary" %>

  <% end %>

</div>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant info</h2>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>
 <% @restaurants.each do |restaurant| %>
    <p>
    <%= link_to restaurant.name, restaurant %>

    <%= link_to restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash-alt"></i>
    <% end  %>
    </p>
<% end %>

<h4>
  <%= link_to 'Add new restaurant', new_restaurant_path %>
</h4>

app/views/restaurants/new.html.erb
<div class="m-4">
  <%= render 'form', restaurant: @restaurant %>

  <h5 class="m-4 pl-4">
    <%= link_to 'Go Back', restaurants_path %>
  </h5>
</div>

app/views/restaurants/show.html.erb
<header class="d-flex">

  <h5 class="p-2">
    <%= link_to 'Edit Restaurant', new_restaurant_path %>
  </h5>
  <h5 class="p-2">
    <%= link_to 'Customer Reviews', restaurant_reviews_path(@restaurant) %>
  </h5>

</header>



<div class="container">
  <h2> <%= @restaurant.name %> </h2>
  <p>Category: <%= @restaurant.category.capitalize %></p>
  <p>Address: <%= @restaurant.address.capitalize %></p>
  <p>Contact: <%= @restaurant.phone_number %></p>
</div>



<div class="d-flex">
  <h5 class="p-2">
  <%= link_to 'Go Back', restaurants_path %>
  </h5>
  <h5 class="p-2">
  <%= link_to 'Add Review', new_restaurant_review_path(@restaurant) %>
  </h5>
</div>

app/views/reviews/_form.html.erb
  <%= simple_form_for [@restaurant, @review] do |f| %>

    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATING  %>
    <%= f.button :submit, class: "btn btn-primary" %>

  <% end %>

app/views/reviews/index.html.erb
<h1>reviews</h1>

<% @reviews.each do |review| %>
<p> <%= review.content %></p>
<p> <%= review.rating %> </p>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>